# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  identityoauth2:
    image: identityoauth2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6001
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
